spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8888
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  type-aliases-package: com.shop.pojo
  global-config:
    db-config:
      table-prefix: tb_
  mapper-locations: classpath*:/mapper/*Mapper.xml



logging:
  level:
    com.shop.mapper: debug
jwt:
  tokenHeader: Authorization
  secret: shop-secret
  expiration: 86400
  tokenHead: Bearer
